### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by carlhako** [gantrim/node-teradata#13]
Hi

I am running debian 8 with node v6.9.4. openjre 7 jdk and jre.

npm-debug.log
[npm-debug.zip](https://github.com/gantrim/node-teradata/files/738058/npm-debug.zip)

I can successfully install java and jdbc packages ok.

output of "npm install teradata --save" I get the following output.

carl@traveltime:~/edwSync$ npm install teradata --save
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> java@0.6.1 install /home/carl/edwSync/node_modules/teradata/node_modules/java
> node-gyp rebuild

make: Entering directory '/home/carl/edwSync/node_modules/teradata/node_modules/java/build'
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../../nan/nan.h:182:0,
                 from ../src/java.h:9,
                 from ../src/java.cpp:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../../nan/nan_maybe_43_inl.h:221:58: warning: ‘v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:3031): Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:188,
                 from ../src/java.h:9,
                 from ../src/java.cpp:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../../nan/nan_implementation_12_inl.h:40:38: warning: ‘static v8::Local<v8::Value> v8::BooleanObject::New(bool)’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:4007): Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ../src/java.h:9:0,
                 from ../src/java.cpp:1:
../../nan/nan.h: At global scope:
../../nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:596:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:596:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:601:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:601:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:602:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:607:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:607:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../../nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../../nan/nan.h:1933:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:2750): Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newByte(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:897:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newShort(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:927:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newLong(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:956:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newChar(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:983:51: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
     v8::Local<v8::Number> val = info[0]->ToNumber();
                                                   ^
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newFloat(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:1019:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
../src/java.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Java::newDouble(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/java.cpp:1044:49: warning: ‘v8::Local<v8::Number> v8::Value::ToNumber() const’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
../src/java.cpp: In function ‘void EIO_AfterCallJs(uv_work_t*)’:
../src/java.cpp:1263:16: warning: ‘v8::TryCatch::TryCatch()’ is deprecated (declared at /home/carl/.node-gyp/6.9.4/include/node/v8.h:6771): Use isolate version [-Wdeprecated-declarations]
   v8::TryCatch tryCatch;
                ^
nodejavabridge_bindings.target.mk:105: recipe for target 'Release/obj.target/nodejavabridge_bindings/src/java.o' failed
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
make: Leaving directory '/home/carl/edwSync/node_modules/teradata/node_modules/java/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/carl/edwSync/node_modules/teradata/node_modules/java
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN edwsync@1.0.0 No description
npm WARN edwsync@1.0.0 No repository field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "teradata" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.6.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/carl/edwSync/npm-debug.log

[npm-debug.zip](https://github.com/gantrim/node-teradata/files/738059/npm-debug.zip)

**Comment by betweenbrain** [comment]
I'm also having this issue with OS X 10.0.5 Java v1.8.0_111
[npm-debug.log.zip](https://github.com/gantrim/node-teradata/files/739655/npm-debug.log.zip)

**Comment by amellnik** [comment]
Also on Windows 7 x64 and Java 1.8.0_121.

**Comment by gantrim** [comment]
it looks like its an issue with the node-java lib. I will look into this further over the next couple days. Any help in debugging is appreciated.
